#公告设置
[app]
    explain         = "本站相关工具及技术仅供个人学习、研究使用。不得用于商业用途，否则后果自负!" #页面使用说明显示
    path            = "/ql/" #QL文件路径设置，一般无需更改
    notice          = "请使用京东APP扫描二维码登录"
    QLip            = "http://127.0.0.1" #青龙面板的ip，部署于一台服务器时不用更改
    QLport          = "5700" #青龙面板的端口，默认为5700
    logName         = "chinnkarahoi_jd_scripts_jd_bean_change" #日志脚本名称
    allowAdd        = "0" #是否允许添加账号（0允许1不允许）不允许添加时则只允许已有账号登录
    allowNum        =  50
    dumpRouterMap   = true
    pushQr          = "http://jd.negev.cn/qr/1.png"


#web服务设置
[server]
	address        = ":5701" #端口号设置
    serverRoot     = "public" #静态目录设置，请勿更改
	serverAgent    = "JDCookie" #服务端UA

#模板设置
[viewer]
Delimiters  =  ["${", "}"] #模板标签，请勿更改
